### ISSUE TITLE
snippets\snippets.json: $action widget attributes need $

### ISSUE THREAD

**Issue by joshuafontany** [joshuafontany/VSCode-TW5-Syntax#16]
Reported by @pmario on talk.tiddlywiki.org:

If I type action-n it allows to add the code snippet below. … But the to parameter needs to be $to – That’s true for all action-widgets and so on.

<$action-navigate to=<<currentTiddler>> scroll="no" />

**Comment by pmario** [comment]
@joshuafontany -- I did just finish all the PRs with the fixes, best practice changes and some formatting for better readability during the initial edit run, when a snippet is inserted. 

There may still be some bugs, but for the beginning the PRs are ready to be reviewed

**Comment by joshuafontany** [comment]
Thank you!

**Comment by joshuafontany** [comment]
Completed! :)
