### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by kookma** [joshuafontany/VSCode-TW5-Syntax#2]
There is no how to install?
Is there this extension available VSCode marketplace?

**Comment by joshuafontany** [comment]
Not yet. Until then, use this method:
https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/

**Comment by linonetwo** [comment]
Can you publish it to the marketplace? This may cause Setting sync error, because it is not actually in the extension list but exists, so setting sync will error says it cannot delete this extension.

**Comment by joshuafontany** [comment]
@linonetwo Thanks for the reminder. I recently fixed some of the more broken regex, and this is stable enough to push to the Marketplace. Possibly enough to use as an in TW highlight scheme. I'll get it up on the Marketplace this week.

**Comment by joshuafontany** [comment]
Published 1.0.0 on the Marketplace. Tested and working.

**Comment by linonetwo** [comment]
Looks very professional! Thank you for this extension.
