### ISSUE TITLE
First line does not work

### ISSUE THREAD

**Issue by kookma** [joshuafontany/VSCode-TW5-Syntax#3]
1. Create a new tiddler like test.tid
2. In the first line write \define xx() this is a test
3. Save

The first line is not highlighted!

If you press enter and create an empty line, move the line above to second line it works

Seems for other inputs like comment, ... is the same

**Comment by joshuafontany** [comment]
The definition syntax file that describes "*.tid Files" (not just tiddlywiki wikitext) requires that there is at least one Field (nominally, `title`) and an empty line before the rest of the text content that is to be parsed as block-wikitext. (Aside - all non-`text` field content in *.tid text file is parsed as in-line wikitext.)

I understand that you could have a *.tid file with only "text content" next to a *.tid.meta file with all the other fields, but this is actually a non-standard situation that TW is flexible enough to handle.

At this time, it is always necessary to have one named field above the text-context in *.tid files.

Best,
Joshua Fontany

**Comment by kookma** [comment]
Thanks for clarification.
